default_stages: [pre-commit]
repos:
    # Common
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-yaml
          - id: sort-simple-yaml
          - id: check-added-large-files

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.38.0
      hooks:
          - id: markdownlint
            args: ['--fix']
            files: \.md$

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.1.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: []

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.5
      hooks:
          - id: shellcheck

    # Frontend

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.1.0'
      hooks:
          - id: prettier
            files: ^frontend/.*\.(js|jsx|ts|tsx|css|scss|json|md)$

    - repo: local
      hooks:
          - id: eslint
            name: ESLint
            entry: npx eslint -c frontend/eslint.config.cjs --no-warn-ignored
            language: system
            files: ^frontend/

    # Backend

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.8
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
            files: ^backend/
          # Run the formatter.
          - id: ruff-format
            files: ^backend/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            args: ['--config-file=backend/mypy.ini', '--no-site-packages']
            files: ^backend/

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.5
      hooks:
          - id: shellcheck
            files: \.sh$
