dgis_base_url: https://catalog.api.2gis.com/
openweather_base_url: https://api.openweathermap.org/data/2.5/weather
history_json: ./history.json

uvicorn_host: '0.0.0.0'
uvicorn_port: 8000
uvicorn_workers: 1
uvicorn_reload: true

openai_model: moonshotai/kimi-k2:free
openai_base_url: https://openrouter.ai/api/v1
openai_temperature: 0.7
openai_max_tokens: 1000

openai_validator_model: moonshotai/kimi-k2:free
openai_validator_base_url: https://openrouter.ai/api/v1
openai_validator_temperature: 0.7
openai_validator_max_tokens: 1000
