dgis_base_url: https://catalog.api.2gis.com/
openweather_base_url: https://api.openweathermap.org/data/2.5/weather
history_dir: ./history

uvicorn_host: '0.0.0.0'
uvicorn_port: 8000
uvicorn_workers: 1
uvicorn_reload: true

cors_allow_origins: ['*']

openai_model: chatgpt-4o-latest
openai_base_url: https://api.openai.com/v1
openai_temperature: 0.7
openai_max_tokens: 1000

openai_validator_model: chatgpt-4o-latest
openai_validator_base_url: https://api.openai.com/v1
openai_validator_temperature: 0.7
openai_validator_max_tokens: 1000

# Cookie
cookie_name: teplitsa_cookie
cookie_max_age: 31536000 # 1 год
