services:
    frontend:
        container_name: teplitsa_frontend
        build:
            context: ../frontend
            dockerfile: ../docker/Dockerfile.frontend
        ports:
            - '80:80'
        networks:
            - teplitsa-net
        depends_on:
            backend:
                condition: service_healthy
        restart: always
    backend:
        container_name: teplitsa_backend
        build:
            context: ../backend
            dockerfile: ../docker/Dockerfile.backend
        networks:
            - teplitsa-net
        volumes:
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost/api/health']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: always
        environment:
            - TEPLITSA_ENV=prod

networks:
    teplitsa-net:
        driver: bridge
