name: Teplitsa application

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Stop previous containers
              run: docker compose -f ./docker/compose.yaml down

            - name: Build and run containers
              run: docker compose -f ./docker/compose.yaml up -d --build
              env:
                  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
                  OPENAI_SUMMARY_KEY: ${{ secrets.OPENAI_SUMMARY_KEY }}
                  OPENAI_VALIDATOR_KEY: ${{ secrets.OPENAI_VALIDATOR_KEY }}
                  TEPLITSA_ENV: ${{ secrets.TEPLITSA_ENV }}
